---
- name: Deploy updated Docker containers to Azure VM
  hosts: all
  become: yes
  gather_facts: no
  vars:
    registry_url: ghcr.io
    compose_project_path: /opt/bridge

  tasks:
    - name: Pull new FastAPI image
      community.docker.docker_image:
        name: "{{ fastapi_image }}"
        source: pull
        force_source: yes

    - name: Pull new Celery image
      community.docker.docker_image:
        name: "{{ celery_image }}"
        source: pull
        force_source: yes

    - name: Update image references in existing docker-compose.yml
      replace:
        path: "{{ compose_project_path }}/docker-compose.yml"
        regexp: 'image:\s*ghcr\.io/.*/fastapi:.*'
        replace: "image: {{ fastapi_image }}"

    - name: Update Celery image reference in existing docker-compose.yml
      replace:
        path: "{{ compose_project_path }}/docker-compose.yml"
        regexp: 'image:\s*ghcr\.io/.*/celery:.*'
        replace: "image: {{ celery_image }}"

    - name: Deploy containers with updated images
      community.docker.docker_compose_v2:
        project_src: "{{ compose_project_path }}"
        state: present
        recreate: always

    - name: Clean up unused Docker images
      community.docker.docker_prune:
        images: yes
        images_filters:
          dangling: false
